usm: 1
kdf:
  name: scrypt
  "n": 32768
  r: 8
  p: 1
  salt: []
crypto:
  cipher: aes-256-gcm
  nonce_bytes: 12
profiles:
  - dev
sign:
  alg: ""
  keyid: ""
  sig: []
secrets:
  dev: {}
metadata:
  created: "2025-08-20T19:39:00Z"
  updated: "2025-08-20T19:39:00Z"
  version: 1
